version: 2.1

jobs:
  build_code: # this can be any name you choose
    docker:
        - image: circleci/python:3.7.0
    steps:
        - checkout
        - run:
              name: Install dependencies
              command: |
                sudo python3 -m venv .
                sudo source bin/activate
                sudo make install
        - run:
              name: run lint
              command: |
                sudo source bin/activate
                sudo make lint
    
workflows:
  lesson3:
    jobs:
      - build_code