version: 2.1

jobs:
  build_code: # this can be any name you choose
    docker:
        - image: circleci/python:3.9.0
    steps:
        - checkout
        - run:
              name: Install dependencies
              command: |
                python3 -m lesson3 .
                source bin/activate
                make install
        - run:
              name: run lint
              command: |
                source bin/activate
                make lint
    
workflows:
  lesson3:
    jobs:
      - build_code